variable "azs" {}
variable "region" {}
variable "public_subnet_cidr" {}
variable "private_subnet_cidr" {}
variable "db_subnet_cidr" {}
variable "vpc_cidr" {}
variable "environment" {}
variable "project_name" {}
variable "common_tags" {}
variable "enable_nat" {}
variable "enable_vpc_flow_logs" {}