name: Terraform Kubeadm Cluster Creation

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::522814728660:role/sivaramakrishna-konka-iam-github-actions
          role-session-name: GitHubActionsTerraform
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Cache Terraform Plugins
        uses: actions/cache@v3
        with:
          path: ~/.terraform.d/plugin-cache
          key: terraform-plugins-${{ runner.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: terraform-plugins-${{ runner.os }}

      - name: Cache Terraform Modules
        uses: actions/cache@v3
        with:
          path: .terraform
          key: terraform-modules-${{ runner.os }}-${{ hashFiles('**/*.tf') }}
          restore-keys: terraform-modules-${{ runner.os }}
  
      - name: Terraform Init
        run: terraform init -plugin-dir=~/.terraform.d/plugin-cache

      - name: Terraform Plan
        run: terraform plan -var-file=environments/development/development.tfvars

      - name: Terraform Apply
        run: terraform apply -var-file=environments/development/development.tfvars
